apiVersion: v2
name: simple-app
description: A simple Helm chart example for GitOps playground

type: application
version: 0.1.0
appVersion: "1.25.3"

maintainers:
  - name: GitOps Playground
    email: example@gitops.local

keywords:
  - gitops
  - example
  - nginx
